[build]
target = "index.html"

[watch]
watch = ["index.html"]

[serve]
# The address to serve on.
address = "::"
# The port to serve on.
port = 80
# Open a browser tab once the initial build is complete.
open = false
# Disable auto-reload of the web app.
no_autoreload = false

[[hooks]]
stage = "pre_build"
command = "tailwindcss"
command_arguments = ["-c", "./tailwind.config.js", "-o", "./tailwind.css"]
